POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Terceiro video de node",
    "description": "Este é o terceiro video de node",
    "duration": 190
}

###

GET http://localhost:3333/videos?search=

###

PUT http://localhost:3333/videos/f2ecfbf5-ec0c-4256-b3d6-a4adbfc60dbf
Content-Type: application/json

{
    "title": "atualização: Segundo video de node!",
    "description": "Este é o segundo video de node!",
    "duration": 180
}

###
DELETE http://localhost:3333/videos/c07d5cf3-dab1-4750-a1a2-6aeac7ea4bda
