POST https://node-do-zero-6m3q.onrender.com/videos
Content-Type: application/json

{
    "title": "Terceiro video de node",
    "description": "Este é o terceiro video de node",
    "duration": 190
}

###

GET https://node-do-zero-6m3q.onrender.com/videos?search=

###

PUT https://node-do-zero-6m3q.onrender.com/videos/5e3d592e-1a8a-4cbf-88d2-d98ec6a326c3
Content-Type: application/json

{
    "title": "Quarto video de node!",
    "description": "Este é o quarto video de node!",
    "duration": 180
}

###
DELETE https://node-do-zero-6m3q.onrender.com/videos/f2ecfbf5-ec0c-4256-b3d6-a4adbfc60dbf
